# Generated by Django 4.0 on 2021-12-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='sevico',
            new_name='servico',
        ),
    ]
